services:
    drf:
        build: .
        container_name: drf
        depends_on:
            pg_db:
                condition: service_healthy
                restart: true
        environment:
            - PYTHONUNBUFFERED=1
        command: python3 manage.py runserver 0.0.0.0:5000
        ports:
            - 127.0.0.1:5000:5000
        links:
            - pg_db
        networks:
            - default
            - backend_network
        
    pg_db:
        image: postgres
        container_name: pg_db
        environment:
            - POSTGRES_DB=${NAME}
            - POSTGRES_USER=${USER}
            - POSTGRES_PASSWORD=${PASSWORD}
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${USER} -d ${NAME}"]
            interval: 30s
            timeout: 10s
            retries: 5
            start_period: 30s
        networks:
            - default
            - backend_network
    
networks:
    backend_network:
        driver: bridge

